import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const srcDir = path.join(root, 'src');
const outputPath = path.join(root, 'Code.js');

try {
  // Read all files in src/
  const files = fs.readdirSync(srcDir)
    .filter(file => file.endsWith('.js'))
    .sort(); // Numeric prefixes (01-, 02-) guarantee correct concatenation order

  let concatenated = '// This file is automatically generated by build-backend.mjs. Do not edit directly.\n\n';

  for (const file of files) {
    const filePath = path.join(srcDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    concatenated += `// ── Begin File: ${file} ──\n${content}\n\n`;
  }

  fs.writeFileSync(outputPath, concatenated, 'utf8');
  console.log(`Backend built successfully! Concatenated ${files.length} files into Code.js`);
} catch (err) {
  console.error('Failed to build backend:', err);
  process.exit(1);
}
